name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "extension/**"

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "extension/package-lock.json"

      - name: Install dependencies
        working-directory: ./extension
        run: npm ci

      - name: Check formatting
        run: npx prettier --check ./extension --ignore-path .gitignore

      - name: Compile
        working-directory: ./extension
        run: npm run compile

      - name: Run tests
        working-directory: ./extension
        run: npm test
