name: Publish Extension

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2 # We need the previous commit to compare versions

      - name: Check version change
        id: version_check
        run: |
          PREV_VERSION=$(git show HEAD^:package.json | jq -r .version)
          CURRENT_VERSION=$(jq -r .version package.json)
          echo "Previous version: $PREV_VERSION"
          echo "Current version: $CURRENT_VERSION"
          if [ "$PREV_VERSION" = "$CURRENT_VERSION" ]; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node.js
        if: steps.version_check.outputs.changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        if: steps.version_check.outputs.changed == 'true'
        run: npm install

      - name: Publish to VS Code Marketplace
        if: steps.version_check.outputs.changed == 'true'
        run: |
          npm install -g @vscode/vsce
          vsce publish -p ${{ secrets.VSCE_TOKEN }}

      - name: Publish to Open VSX
        if: steps.version_check.outputs.changed == 'true'
        run: |
          npm install -g ovsx
          ovsx publish -p ${{ secrets.OPEN_VSX_TOKEN }}
